addSbtPlugin("com.eed3si9n"      % "sbt-projectmatrix"   % "0.10.1")
addSbtPlugin("org.scala-js"      % "sbt-scalajs"         % "1.17.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.5.3")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"        % "0.13.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.10.0")
addSbtPlugin("com.github.sbt"    % "sbt-ci-release"      % "1.9.2")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalajs-bundler" % "0.21.1")
